version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/backend_server
hooks:
  Application start:
    - location: register_with_elb.sh
  AfterInstall:
    - location: start_server
      timeout: 300
